### ISSUE TITLE
wrong module path

### ISSUE THREAD

**Issue by kirrie** [kylefarris/node-querybuilder#16]
node version: v8.7.0
```
/Users/.../node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

Error: Cannot find module '../../node_modules/mysql/lib/protocol/SqlString.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at qb_escape (/Users/kirrie/Documents/Github/signal/heart-api/node_modules/node-querybuilder/drivers/mysql/query_builder.js:281:27)
    at Object._where (/Users/kirrie/Documents/Github/signal/heart-api/node_modules/node-querybuilder/drivers/mysql/query_builder.js:587:35)
    at Object.where (/Users/kirrie/Documents/Github/signal/heart-api/node_modules/node-querybuilder/drivers/mysql/query_builder.js:507:25)
    at pool.get_connection.connection (/Users/kirrie/Documents/Github/signal/heart-api/libraries/model.js:244:7)
    at nqb.pool.getConnection (/Users/kirrie/Documents/Github/signal/heart-api/node_modules/node-querybuilder/drivers/mysql/adapters.js:172:25)
    at Handshake.onConnect [as _callback] (/Users/kirrie/Documents/Github/signal/heart-api/node_modules/mysql/lib/Pool.js:59:7)
```

maybe path should be 'mysql/lib/protocol/SqlString.js' not start with '../../node_modules'.

**Comment by kylefarris** [comment]
This was fixed in version v1.2.0
