### ISSUE TITLE
[v2] insert_batch should resolve if passed empty array. 

### ISSUE THREAD

**Issue by Flamenco** [kylefarris/node-querybuilder#42]
Currently an error is thrown if rows to insert is empty.  I would like if this did not throw, and simply resolved.
But if it must, the error should be 'No rows specified to insert' or such.

```
TypeError: cb is not a function
    at Query._connection.query (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/node-querybuilder/drivers/mysql/query_exec.js:33:17)
    at Query.<anonymous> (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/steven/dev/projects/other/badges/badges-admin/node_modules/mysql/lib/Connection.js:502:10)
 ```

**Comment by kylefarris** [comment]
This is the same as #36. You can see my comments there.
