### ISSUE TITLE
qb.select is not a function

### ISSUE THREAD

**Issue by shajeermhmmd** [kylefarris/node-querybuilder#7]
Hi,
I have a problem with"node-querybuilder ", ie, select is not a function, bellow giving my code,kindly request you to check and I hope you will give a solution for this issue ASAP.

var qb = require('node-querybuilder').QueryBuilder({
	  	    connectionLimit : 100,
		    host     : 'localhost',
		    user     : 'root',
		    password : '',
		    database : 'address_book',
		    debug    : false,
		    pool_size: 50
		}, 'mysql', 'pool');
	    qb.select('*').get('users', function(err,response) {
	        if (err) return console.error("Uh oh! Couldn't get results: " + err.msg);	 
	        console.log("Query Ran: " + qb.last_query());	 
	        return response;
		});

Result (error)
----------------
<body>
        <h1>qb.select is not a function</h1>
        <h2></h2>
        <pre>TypeError: qb.select is not a function
    at Object.db_connect (E:\ExperionProjects\trials\myapp\config\connect_db.js:17:9)
    at E:\ExperionProjects\trials\myapp\routes\test.js:29:28
    at Layer.handle [as handle_request] (E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\layer.js:95:5)
    at E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\index.js:330:12)
    at next (E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (E:\ExperionProjects\trials\myapp\node_modules\express\lib\router\index.js:176:3)</pre>
    </body>

**Comment by kylefarris** [comment]
Hey @shajeermhmmd,

You've setup the QueryBuilder instance to create a pool of connections (preferred way) but you're attempting to use the library as if you set it up for a single connection. You need to get a connection from the pool first (see: https://github.com/kylefarris/node-querybuilder#get_connection)

You code should be as follows:

```javascript
var pool= require('node-querybuilder').QueryBuilder({
    connectionLimit : 100,
    host : 'localhost',
    user : 'root',
    password : '',
    database : 'address_book',
    debug : false,
    pool_size: 50
}, 'mysql', 'pool');

pool.get_connection(function(qb) {
    qb.select('*').get('users', function(err,response) {
        qb.release(); // <-- make sure to do this when you're done with each series of queries
        if (err) return console.error("Uh oh! Couldn't get results: " + err.msg);
        console.log("Query Ran: " + qb.last_query());
        return response;
    });
});
```

Also, if you're going to be selecting all fields, there's no need to write `.select('*')`; you can simply omit it like this:  `qb.get('users', ...` and it will work as expected.
